### PR TITLE
Bring in deserialization fixes from master

### PR DESCRIPTION
**Pull request by saethlin**

### CODE REVIEW

**Comment by tinaun** [comment]
i already fixed this in an upcoming patch, but thanks!

**Comment by saethlin** [comment]
It would be super cool if you pushed more often :)

**Comment by tinaun** [comment]
it would be super cool if i stopped writing huge commits that change lots of things at once, yes

sorry about that

**Comment by saethlin** [comment]
Can you enable issues? I'm having some serious ones and I would like to talk about what the heck is going on.

**Pull request closed without merging**
